# Generated by Django 3.1.2 on 2020-11-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destino', '0002_auto_20201102_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='destino',
            name='url',
            field=models.URLField(default='', max_length=100),
        ),
    ]
